version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MY_ROUTER_KEY: ${MY_ROUTER_KEY}
    ports:
      - "8000:8000"
    env_file:
      - .env